# Generated by Django 3.2.7 on 2021-09-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_alter_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='category1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categor1', to='categorys.category'),
        ),
        migrations.AddField(
            model_name='contact',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categor2', to='categorys.category'),
        ),
    ]
