# Generated by Django 3.2.7 on 2021-09-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0003_auto_20210925_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='category2',
        ),
        migrations.AddField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название курса')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание курса')),
                ('logo', models.ImageField(null=True, upload_to='media', verbose_name='logo/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='categorys.category')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch1', to='categorys.course'),
        ),
        migrations.AddField(
            model_name='contact',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact1', to='categorys.course'),
        ),
    ]
