# Generated by Django 3.2.7 on 2021-09-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0004_auto_20210925_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
