# Generated by Django 3.2.7 on 2021-10-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0009_alter_contact_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
